- hosts:
  - all
  tasks:
  - name: install packages
    package:
      name:
        - podman
        - nginx
        - certbot
        - python3-certbot-nginx.noarch
      state: latest


  - name: print certbot command
    debug:
      msg: "certbot --nginx -d www.warsztaty.linux.org.pl,{% for student in students %}{{ student }}.warsztaty.linux.org.pl{% if not loop.last %},{% endif %}{% endfor %}"

  - pause:

  - name: copy vhost
    template:
      src: vhost.conf
      dest: "/etc/nginx/conf.d/vhost.conf"
    notify:
      - restart nginx

  - name: start nginx
    service:
      name: nginx
      state: started

  - name: create user
    user:
      name: "container"
      state: present
    register: _user

  - name: run loginctl enable-linger container
    command: "loginctl enable-linger container"

  - name: Run container
    vars:
      id: "{{ '%02d' | format(item[4:]|int) }}"
    #command: podman run --rm -d --name user-{{ item }} -p 82{{ id }}:22 -p 81{{ id }}:5000 -p 80{{ id }}:80 registry.gitlab.exphost.pl/torgiren/fedora-sshd:latest
    loop: "{{ students }}"
    containers.podman.podman_container:
      name: user-{{ item }}
      image: registry.gitlab.exphost.pl/torgiren/fedora-sshd:latest
      state: started
      ports:
        - 82{{ id }}:22
        - 81{{ id }}:5000
        - 80{{ id }}:80
      hostname: user-{{ item }}
      rm: yes
      tty: yes
      interactive: yes
      detach: yes
    loop: "{{ students }}"
    become: yes
    become_user: container

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

